# Generated by Django 5.0.6 on 2025-10-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtteremKoltseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koltseg_tipus', models.CharField(choices=[('szallitas', 'Szállítás'), ('csomagolas', 'Csomagolás'), ('borravalo', 'Borravaló'), ('egyeb', 'Egyéb')], max_length=20, verbose_name='Költség típusa')),
                ('osszeg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Összeg (HUF)')),
                ('etterem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koltsegek', to='catalog.etterem', verbose_name='Étterem')),
            ],
            options={
                'verbose_name': 'Étterem költség',
                'verbose_name_plural': 'Étterem költségek',
                'indexes': [models.Index(fields=['koltseg_tipus'], name='billing_ett_koltseg_e91098_idx')],
            },
        ),
    ]
