# Generated by Django 5.2.7 on 2025-10-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0003_alter_etel_options_alter_etterem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etteremkoltseg',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='etteremkoltseg',
            name='billing_ett_koltseg_e91098_idx',
        ),
        migrations.AlterField(
            model_name='etteremkoltseg',
            name='etterem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koltsegek', to='catalog.etterem'),
        ),
        migrations.AlterField(
            model_name='etteremkoltseg',
            name='koltseg_tipus',
            field=models.CharField(choices=[('szallitas', 'Szállítás'), ('csomagolas', 'Csomagolás'), ('borravalo', 'Borravaló'), ('egyeb', 'Egyéb')], max_length=30),
        ),
        migrations.AlterField(
            model_name='etteremkoltseg',
            name='osszeg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
