# Generated by Django 5.0.6 on 2025-10-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtteremEtelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ár (HUF)')),
                ('szallitas_ido', models.DurationField(blank=True, null=True, verbose_name='Szállítási idő')),
                ('felhaszn_ertekelesek', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Felhasználói értékelések (átlag)')),
                ('promocio', models.CharField(blank=True, max_length=255, verbose_name='Promóció')),
                ('etel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etterem_info', to='catalog.etel', verbose_name='Étel')),
                ('etterem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etel_info', to='catalog.etterem', verbose_name='Étterem')),
            ],
            options={
                'verbose_name': 'Étterem–Étel információ',
                'verbose_name_plural': 'Étterem–Étel információk',
            },
        ),
        migrations.CreateModel(
            name='Mentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letrehozva', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('etel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentesek', to='catalog.etel', verbose_name='Étel')),
            ],
            options={
                'verbose_name': 'Mentés',
                'verbose_name_plural': 'Mentések',
                'ordering': ['-letrehozva'],
            },
        ),
    ]
