# Generated by Django 5.0.6 on 2025-10-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compare', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentes',
            name='felhasznalo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentesek', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.AddIndex(
            model_name='etteremetelinfo',
            index=models.Index(fields=['etel'], name='compare_ett_etel_id_e32dce_idx'),
        ),
        migrations.AddIndex(
            model_name='etteremetelinfo',
            index=models.Index(fields=['etterem'], name='compare_ett_etterem_c794d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etteremetelinfo',
            unique_together={('etel', 'etterem')},
        ),
        migrations.AlterUniqueTogether(
            name='mentes',
            unique_together={('felhasznalo', 'etel')},
        ),
    ]
