# Generated by Django 5.0.6 on 2025-10-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_add_platform'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='etteremetelinfo',
            new_name='compare_ett_platfor_bd6875_idx',
            old_name='compare_ett_platform_idx',
        ),
        migrations.AlterField(
            model_name='etteremetelinfo',
            name='platform',
            field=models.CharField(choices=[('wolt', 'Wolt'), ('foodora', 'Foodora'), ('bolt', 'Bolt Food'), ('egyeb', 'Egyéb')], default='egyeb', max_length=20, verbose_name='Platform'),
        ),
    ]
