# Generated by Django 5.0.6 on 2025-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Étel neve')),
                ('leiras', models.TextField(blank=True, verbose_name='Leírás')),
                ('kategoria', models.CharField(blank=True, max_length=120, verbose_name='Kategória')),
                ('kep_url', models.URLField(blank=True, verbose_name='Kép URL')),
            ],
            options={
                'verbose_name': 'Étel',
                'verbose_name_plural': 'Ételek',
                'indexes': [models.Index(fields=['nev', 'kategoria'], name='catalog_ete_nev_4581c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Etterem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=200, verbose_name='Étterm neve')),
                ('cim', models.CharField(blank=True, max_length=255, verbose_name='Cím')),
                ('platform', models.CharField(choices=[('wolt', 'Wolt'), ('foodora', 'Foodora'), ('egyeb', 'Egyéb')], default='wolt', max_length=20, verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Étterem',
                'verbose_name_plural': 'Éttermek',
                'indexes': [models.Index(fields=['nev'], name='catalog_ett_nev_dd5d08_idx'), models.Index(fields=['platform'], name='catalog_ett_platfor_b61832_idx')],
            },
        ),
    ]
