# Generated by Django 5.2.7 on 2025-10-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etel',
            options={'ordering': ('nev',), 'verbose_name': 'Étel', 'verbose_name_plural': 'Ételek'},
        ),
        migrations.AlterModelOptions(
            name='etterem',
            options={'ordering': ('nev',), 'verbose_name': 'Étterem', 'verbose_name_plural': 'Éttermek'},
        ),
        migrations.RemoveIndex(
            model_name='etel',
            name='catalog_ete_nev_4581c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='etterem',
            name='catalog_ett_nev_dd5d08_idx',
        ),
        migrations.RemoveIndex(
            model_name='etterem',
            name='catalog_ett_platfor_b61832_idx',
        ),
        migrations.AlterField(
            model_name='etel',
            name='kategoria',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kategória'),
        ),
        migrations.AlterField(
            model_name='etel',
            name='nev',
            field=models.CharField(max_length=150, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='etterem',
            name='cim',
            field=models.CharField(max_length=255, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='etterem',
            name='nev',
            field=models.CharField(max_length=150, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='etterem',
            name='platform',
            field=models.CharField(choices=[('wolt', 'Wolt'), ('foodora', 'Foodora'), ('bolt', 'Bolt Food')], help_text='Pl.: Wolt / Foodora / Bolt Food', max_length=20, verbose_name='Platform'),
        ),
    ]
