# Generated by Django 5.2.7 on 2025-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_etel_options_alter_etterem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='etterem',
            options={},
        ),
        migrations.AddField(
            model_name='etterem',
            name='platform_logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='etterem',
            name='platform_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='etel',
            name='kategoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='etel',
            name='kep_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='etel',
            name='leiras',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='etel',
            name='nev',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='etterem',
            name='cim',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='etterem',
            name='nev',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='etterem',
            name='platform',
            field=models.CharField(choices=[('wolt', 'Wolt'), ('foodora', 'Foodora'), ('bolt', 'Bolt Food'), ('egyeb', 'Egyéb')], default='egyeb', max_length=20),
        ),
    ]
